package xyz.mdhv.formanalyser.body

/**
 * Schematic atlas geometry for the 52-region contract (Phase 3 §A). Viewport is 1000×2000 units
 * per side (FRONT/BACK), body centered, head at top.
 *
 * v0 geometry is deliberately simple: each region is an axis-aligned rounded rectangle. That is
 * enough to satisfy every integrity requirement (all 52 present, exact left/right mirrors,
 * finger-sized ≥60×60 boxes, zero overlaps, centroid hit-tests) while staying pure JVM and
 * headless-testable. Hand-drawn SVG paths can replace this later via the
 * `body_atlas.override.json` drop-in seam without touching IDs or consumers.
 *
 * Author-once-mirror-right: only left-side and centerline rects are authored; right-side rects are
 * generated by `x' = WIDTH − x − w`, so symmetry is guaranteed, not hoped for.
 */
data class RegionShape(
    val id: String,
    val face: BodyFace,
    val x: Double,
    val y: Double,
    val w: Double,
    val h: Double,
) {
    val centerX: Double get() = x + w / 2
    val centerY: Double get() = y + h / 2
    fun contains(px: Double, py: Double): Boolean = px >= x && px < x + w && py >= y && py < y + h
    fun overlaps(o: RegionShape): Boolean =
        face == o.face && x < o.x + o.w && o.x < x + w && y < o.y + o.h && o.y < y + h
}

object BodyAtlas {
    const val WIDTH = 1000.0
    const val HEIGHT = 2000.0

    // Authored geometry: centerline + left-side regions only. (x, y, w, h) in viewport units.
    private data class Authored(val id: String, val face: BodyFace, val x: Double, val y: Double, val w: Double, val h: Double)

    private val authored: List<Authored> = listOf(
        // ---- FRONT: centerline ----
        Authored(RegionIds.NECK_ANT, BodyFace.FRONT, 430.0, 150.0, 140.0, 90.0),
        Authored(RegionIds.ABS_UPPER, BodyFace.FRONT, 400.0, 400.0, 200.0, 110.0),
        Authored(RegionIds.ABS_LOWER, BodyFace.FRONT, 400.0, 530.0, 200.0, 110.0),
        // ---- FRONT: left side (right generated) ----
        Authored(RegionIds.DELT_LAT_L, BodyFace.FRONT, 180.0, 260.0, 90.0, 90.0),
        Authored(RegionIds.DELT_ANT_L, BodyFace.FRONT, 280.0, 260.0, 90.0, 90.0),
        Authored(RegionIds.PEC_L, BodyFace.FRONT, 380.0, 270.0, 110.0, 110.0),
        Authored(RegionIds.BICEPS_L, BodyFace.FRONT, 210.0, 370.0, 90.0, 120.0),
        Authored(RegionIds.FOREARM_FLEX_L, BodyFace.FRONT, 190.0, 510.0, 90.0, 140.0),
        Authored(RegionIds.HAND_L, BodyFace.FRONT, 180.0, 670.0, 90.0, 90.0),
        Authored(RegionIds.OBLIQUE_L, BodyFace.FRONT, 310.0, 430.0, 80.0, 180.0),
        Authored(RegionIds.HIP_L, BodyFace.FRONT, 330.0, 660.0, 110.0, 90.0),
        Authored(RegionIds.QUAD_L, BodyFace.FRONT, 330.0, 770.0, 120.0, 220.0),
        Authored(RegionIds.KNEE_L, BodyFace.FRONT, 340.0, 1010.0, 100.0, 80.0),
        Authored(RegionIds.SHIN_L, BodyFace.FRONT, 345.0, 1110.0, 90.0, 220.0),
        // ---- BACK: centerline ----
        Authored(RegionIds.NECK_POST, BodyFace.BACK, 430.0, 140.0, 140.0, 90.0),
        // ---- BACK: left side (right generated) ----
        Authored(RegionIds.TRAP_UPPER_L, BodyFace.BACK, 310.0, 240.0, 120.0, 70.0),
        Authored(RegionIds.TRAP_MID_L, BodyFace.BACK, 310.0, 320.0, 110.0, 80.0),
        Authored(RegionIds.TRAP_LOWER_L, BodyFace.BACK, 330.0, 410.0, 100.0, 90.0),
        Authored(RegionIds.RHOMBOID_L, BodyFace.BACK, 430.0, 320.0, 65.0, 110.0),
        Authored(RegionIds.DELT_POST_L, BodyFace.BACK, 190.0, 250.0, 100.0, 90.0),
        Authored(RegionIds.ROTATOR_CUFF_L, BodyFace.BACK, 200.0, 350.0, 100.0, 90.0),
        Authored(RegionIds.LAT_L, BodyFace.BACK, 310.0, 510.0, 120.0, 150.0),
        Authored(RegionIds.ERECTOR_L, BodyFace.BACK, 433.0, 440.0, 62.0, 210.0),
        Authored(RegionIds.TRICEPS_L, BodyFace.BACK, 200.0, 450.0, 90.0, 130.0),
        Authored(RegionIds.FOREARM_EXT_L, BodyFace.BACK, 190.0, 600.0, 90.0, 140.0),
        Authored(RegionIds.GLUTE_L, BodyFace.BACK, 330.0, 680.0, 140.0, 110.0),
        Authored(RegionIds.HAMSTRING_L, BodyFace.BACK, 330.0, 810.0, 120.0, 200.0),
        Authored(RegionIds.CALF_L, BodyFace.BACK, 340.0, 1030.0, 100.0, 200.0),
    )

    /** All 52 regions: authored centerline + left, plus mirrored right. */
    val regions: List<RegionShape> = buildList {
        for (a in authored) {
            add(RegionShape(a.id, a.face, a.x, a.y, a.w, a.h))
            if (a.id.endsWith("_l")) {
                val rid = a.id.dropLast(2) + "_r"
                add(RegionShape(rid, a.face, WIDTH - a.x - a.w, a.y, a.w, a.h))
            }
        }
    }

    val byId: Map<String, RegionShape> = regions.associateBy { it.id }

    fun forFace(face: BodyFace): List<RegionShape> = regions.filter { it.face == face }

    /** First (only, by the no-overlap invariant) region containing the point, or null. */
    fun hitTest(face: BodyFace, x: Double, y: Double): RegionShape? =
        forFace(face).firstOrNull { it.contains(x, y) }
}
